name: sudoku_game
description: A Flutter Sudoku game with MVVM/Provider architecture.
publish_to: 'none'
version: 1.3.2+1
environment:
  sdk: ">=3.1.0 <4.0.0"

# Flutter 3.x compatible

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  shared_preferences: ^2.2.3
  flutter_confetti: ^0.5.1
  reward_popup: ^0.0.7
  liquid_glass_renderer: ^0.1.1-dev.26

  # Cupertino icons for iOS style icons
  cupertino_icons: ^1.0.6
  intl: ^0.20.2
  motor: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
